/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTarefasRouteImport } from './routes/_authenticated/app.tarefas'
import { Route as AuthenticatedAppPedidosRouteImport } from './routes/_authenticated/app.pedidos'
import { Route as AuthenticatedAppMateriaisRouteImport } from './routes/_authenticated/app.materiais'
import { Route as AuthenticatedAppEcossistemaRouteImport } from './routes/_authenticated/app.ecossistema'
import { Route as AuthenticatedAppComunidadeRouteImport } from './routes/_authenticated/app.comunidade'
import { Route as AuthenticatedAppAulasRouteImport } from './routes/_authenticated/app.aulas'
import { Route as AuthenticatedAppAulasCourseIdRouteImport } from './routes/_authenticated/app.aulas.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_authenticated/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTarefasRoute = AuthenticatedAppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPedidosRoute = AuthenticatedAppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMateriaisRoute =
  AuthenticatedAppMateriaisRouteImport.update({
    id: '/materiais',
    path: '/materiais',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEcossistemaRoute =
  AuthenticatedAppEcossistemaRouteImport.update({
    id: '/ecossistema',
    path: '/ecossistema',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComunidadeRoute =
  AuthenticatedAppComunidadeRouteImport.update({
    id: '/comunidade',
    path: '/comunidade',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAulasRoute = AuthenticatedAppAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAulasCourseIdRoute =
  AuthenticatedAppAulasCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAppAulasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/aulas': typeof AuthenticatedAppAulasRouteWithChildren
  '/app/comunidade': typeof AuthenticatedAppComunidadeRoute
  '/app/ecossistema': typeof AuthenticatedAppEcossistemaRoute
  '/app/materiais': typeof AuthenticatedAppMateriaisRoute
  '/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/aulas/$courseId': typeof AuthenticatedAppAulasCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/aulas': typeof AuthenticatedAppAulasRouteWithChildren
  '/app/comunidade': typeof AuthenticatedAppComunidadeRoute
  '/app/ecossistema': typeof AuthenticatedAppEcossistemaRoute
  '/app/materiais': typeof AuthenticatedAppMateriaisRoute
  '/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/aulas/$courseId': typeof AuthenticatedAppAulasCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/aulas': typeof AuthenticatedAppAulasRouteWithChildren
  '/_authenticated/app/comunidade': typeof AuthenticatedAppComunidadeRoute
  '/_authenticated/app/ecossistema': typeof AuthenticatedAppEcossistemaRoute
  '/_authenticated/app/materiais': typeof AuthenticatedAppMateriaisRoute
  '/_authenticated/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/_authenticated/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/aulas/$courseId': typeof AuthenticatedAppAulasCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/aulas'
    | '/app/comunidade'
    | '/app/ecossistema'
    | '/app/materiais'
    | '/app/pedidos'
    | '/app/tarefas'
    | '/app/'
    | '/app/aulas/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/aulas'
    | '/app/comunidade'
    | '/app/ecossistema'
    | '/app/materiais'
    | '/app/pedidos'
    | '/app/tarefas'
    | '/app'
    | '/app/aulas/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/app'
    | '/_authenticated/app/aulas'
    | '/_authenticated/app/comunidade'
    | '/_authenticated/app/ecossistema'
    | '/_authenticated/app/materiais'
    | '/_authenticated/app/pedidos'
    | '/_authenticated/app/tarefas'
    | '/_authenticated/app/'
    | '/_authenticated/app/aulas/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tarefas': {
      id: '/_authenticated/app/tarefas'
      path: '/tarefas'
      fullPath: '/app/tarefas'
      preLoaderRoute: typeof AuthenticatedAppTarefasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pedidos': {
      id: '/_authenticated/app/pedidos'
      path: '/pedidos'
      fullPath: '/app/pedidos'
      preLoaderRoute: typeof AuthenticatedAppPedidosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/materiais': {
      id: '/_authenticated/app/materiais'
      path: '/materiais'
      fullPath: '/app/materiais'
      preLoaderRoute: typeof AuthenticatedAppMateriaisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ecossistema': {
      id: '/_authenticated/app/ecossistema'
      path: '/ecossistema'
      fullPath: '/app/ecossistema'
      preLoaderRoute: typeof AuthenticatedAppEcossistemaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comunidade': {
      id: '/_authenticated/app/comunidade'
      path: '/comunidade'
      fullPath: '/app/comunidade'
      preLoaderRoute: typeof AuthenticatedAppComunidadeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/aulas': {
      id: '/_authenticated/app/aulas'
      path: '/aulas'
      fullPath: '/app/aulas'
      preLoaderRoute: typeof AuthenticatedAppAulasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/aulas/$courseId': {
      id: '/_authenticated/app/aulas/$courseId'
      path: '/$courseId'
      fullPath: '/app/aulas/$courseId'
      preLoaderRoute: typeof AuthenticatedAppAulasCourseIdRouteImport
      parentRoute: typeof AuthenticatedAppAulasRoute
    }
  }
}

interface AuthenticatedAppAulasRouteChildren {
  AuthenticatedAppAulasCourseIdRoute: typeof AuthenticatedAppAulasCourseIdRoute
}

const AuthenticatedAppAulasRouteChildren: AuthenticatedAppAulasRouteChildren = {
  AuthenticatedAppAulasCourseIdRoute: AuthenticatedAppAulasCourseIdRoute,
}

const AuthenticatedAppAulasRouteWithChildren =
  AuthenticatedAppAulasRoute._addFileChildren(
    AuthenticatedAppAulasRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAulasRoute: typeof AuthenticatedAppAulasRouteWithChildren
  AuthenticatedAppComunidadeRoute: typeof AuthenticatedAppComunidadeRoute
  AuthenticatedAppEcossistemaRoute: typeof AuthenticatedAppEcossistemaRoute
  AuthenticatedAppMateriaisRoute: typeof AuthenticatedAppMateriaisRoute
  AuthenticatedAppPedidosRoute: typeof AuthenticatedAppPedidosRoute
  AuthenticatedAppTarefasRoute: typeof AuthenticatedAppTarefasRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAulasRoute: AuthenticatedAppAulasRouteWithChildren,
  AuthenticatedAppComunidadeRoute: AuthenticatedAppComunidadeRoute,
  AuthenticatedAppEcossistemaRoute: AuthenticatedAppEcossistemaRoute,
  AuthenticatedAppMateriaisRoute: AuthenticatedAppMateriaisRoute,
  AuthenticatedAppPedidosRoute: AuthenticatedAppPedidosRoute,
  AuthenticatedAppTarefasRoute: AuthenticatedAppTarefasRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
