/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTarefasRouteImport } from './routes/_authenticated/app.tarefas'
import { Route as AuthenticatedAppPedidosRouteImport } from './routes/_authenticated/app.pedidos'
import { Route as AuthenticatedAppMateriaisRouteImport } from './routes/_authenticated/app.materiais'
import { Route as AuthenticatedAppEcossistemaRouteImport } from './routes/_authenticated/app.ecossistema'
import { Route as AuthenticatedAppComunidadeRouteImport } from './routes/_authenticated/app.comunidade'
import { Route as AuthenticatedAppBoasVindasRouteImport } from './routes/_authenticated/app.boas-vindas'
import { Route as AuthenticatedAppAulasRouteImport } from './routes/_authenticated/app.aulas'
import { Route as AuthenticatedAppAulasCourseIdRouteImport } from './routes/_authenticated/app.aulas.$courseId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTarefasRoute = AuthenticatedAppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPedidosRoute = AuthenticatedAppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMateriaisRoute =
  AuthenticatedAppMateriaisRouteImport.update({
    id: '/materiais',
    path: '/materiais',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEcossistemaRoute =
  AuthenticatedAppEcossistemaRouteImport.update({
    id: '/ecossistema',
    path: '/ecossistema',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComunidadeRoute =
  AuthenticatedAppComunidadeRouteImport.update({
    id: '/comunidade',
    path: '/comunidade',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBoasVindasRoute =
  AuthenticatedAppBoasVindasRouteImport.update({
    id: '/boas-vindas',
    path: '/boas-vindas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAulasRoute = AuthenticatedAppAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAulasCourseIdRoute =
  AuthenticatedAppAulasCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAppAulasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/aulas': typeof AuthenticatedAppAulasRouteWithChildren
  '/app/boas-vindas': typeof AuthenticatedAppBoasVindasRoute
  '/app/comunidade': typeof AuthenticatedAppComunidadeRoute
  '/app/ecossistema': typeof AuthenticatedAppEcossistemaRoute
  '/app/materiais': typeof AuthenticatedAppMateriaisRoute
  '/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/aulas/$courseId': typeof AuthenticatedAppAulasCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/aulas': typeof AuthenticatedAppAulasRouteWithChildren
  '/app/boas-vindas': typeof AuthenticatedAppBoasVindasRoute
  '/app/comunidade': typeof AuthenticatedAppComunidadeRoute
  '/app/ecossistema': typeof AuthenticatedAppEcossistemaRoute
  '/app/materiais': typeof AuthenticatedAppMateriaisRoute
  '/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/aulas/$courseId': typeof AuthenticatedAppAulasCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/aulas': typeof AuthenticatedAppAulasRouteWithChildren
  '/_authenticated/app/boas-vindas': typeof AuthenticatedAppBoasVindasRoute
  '/_authenticated/app/comunidade': typeof AuthenticatedAppComunidadeRoute
  '/_authenticated/app/ecossistema': typeof AuthenticatedAppEcossistemaRoute
  '/_authenticated/app/materiais': typeof AuthenticatedAppMateriaisRoute
  '/_authenticated/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/_authenticated/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/aulas/$courseId': typeof AuthenticatedAppAulasCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/aulas'
    | '/app/boas-vindas'
    | '/app/comunidade'
    | '/app/ecossistema'
    | '/app/materiais'
    | '/app/pedidos'
    | '/app/tarefas'
    | '/app/'
    | '/app/aulas/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/aulas'
    | '/app/boas-vindas'
    | '/app/comunidade'
    | '/app/ecossistema'
    | '/app/materiais'
    | '/app/pedidos'
    | '/app/tarefas'
    | '/app'
    | '/app/aulas/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/aulas'
    | '/_authenticated/app/boas-vindas'
    | '/_authenticated/app/comunidade'
    | '/_authenticated/app/ecossistema'
    | '/_authenticated/app/materiais'
    | '/_authenticated/app/pedidos'
    | '/_authenticated/app/tarefas'
    | '/_authenticated/app/'
    | '/_authenticated/app/aulas/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tarefas': {
      id: '/_authenticated/app/tarefas'
      path: '/tarefas'
      fullPath: '/app/tarefas'
      preLoaderRoute: typeof AuthenticatedAppTarefasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pedidos': {
      id: '/_authenticated/app/pedidos'
      path: '/pedidos'
      fullPath: '/app/pedidos'
      preLoaderRoute: typeof AuthenticatedAppPedidosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/materiais': {
      id: '/_authenticated/app/materiais'
      path: '/materiais'
      fullPath: '/app/materiais'
      preLoaderRoute: typeof AuthenticatedAppMateriaisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ecossistema': {
      id: '/_authenticated/app/ecossistema'
      path: '/ecossistema'
      fullPath: '/app/ecossistema'
      preLoaderRoute: typeof AuthenticatedAppEcossistemaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comunidade': {
      id: '/_authenticated/app/comunidade'
      path: '/comunidade'
      fullPath: '/app/comunidade'
      preLoaderRoute: typeof AuthenticatedAppComunidadeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/boas-vindas': {
      id: '/_authenticated/app/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/app/boas-vindas'
      preLoaderRoute: typeof AuthenticatedAppBoasVindasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/aulas': {
      id: '/_authenticated/app/aulas'
      path: '/aulas'
      fullPath: '/app/aulas'
      preLoaderRoute: typeof AuthenticatedAppAulasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/aulas/$courseId': {
      id: '/_authenticated/app/aulas/$courseId'
      path: '/$courseId'
      fullPath: '/app/aulas/$courseId'
      preLoaderRoute: typeof AuthenticatedAppAulasCourseIdRouteImport
      parentRoute: typeof AuthenticatedAppAulasRoute
    }
  }
}

interface AuthenticatedAppAulasRouteChildren {
  AuthenticatedAppAulasCourseIdRoute: typeof AuthenticatedAppAulasCourseIdRoute
}

const AuthenticatedAppAulasRouteChildren: AuthenticatedAppAulasRouteChildren = {
  AuthenticatedAppAulasCourseIdRoute: AuthenticatedAppAulasCourseIdRoute,
}

const AuthenticatedAppAulasRouteWithChildren =
  AuthenticatedAppAulasRoute._addFileChildren(
    AuthenticatedAppAulasRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAulasRoute: typeof AuthenticatedAppAulasRouteWithChildren
  AuthenticatedAppBoasVindasRoute: typeof AuthenticatedAppBoasVindasRoute
  AuthenticatedAppComunidadeRoute: typeof AuthenticatedAppComunidadeRoute
  AuthenticatedAppEcossistemaRoute: typeof AuthenticatedAppEcossistemaRoute
  AuthenticatedAppMateriaisRoute: typeof AuthenticatedAppMateriaisRoute
  AuthenticatedAppPedidosRoute: typeof AuthenticatedAppPedidosRoute
  AuthenticatedAppTarefasRoute: typeof AuthenticatedAppTarefasRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAulasRoute: AuthenticatedAppAulasRouteWithChildren,
  AuthenticatedAppBoasVindasRoute: AuthenticatedAppBoasVindasRoute,
  AuthenticatedAppComunidadeRoute: AuthenticatedAppComunidadeRoute,
  AuthenticatedAppEcossistemaRoute: AuthenticatedAppEcossistemaRoute,
  AuthenticatedAppMateriaisRoute: AuthenticatedAppMateriaisRoute,
  AuthenticatedAppPedidosRoute: AuthenticatedAppPedidosRoute,
  AuthenticatedAppTarefasRoute: AuthenticatedAppTarefasRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
